# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'nassi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nassi
  pod 'Alamofire', '~> 5.0'
  pod 'ResourceKit'
  pod "youtube-ios-player-helper", "~> 1.0.0"
  pod "KRProgressHUD"
end
