# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'nassi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nassi
  pod 'Alamofire', '~> 4.4'
  pod 'ResourceKit'
  pod "youtube-ios-player-helper", "~> 0.1.4"
  pod "KRProgressHUD"
end
