// This is a generated file 
// Generated by ResouceKit 
// You can write custom imoprt XXXX logic
import UIKit
protocol XibProtocol {
	var name: String { get } 
	 func nib() -> UINib
}
extension UITableView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension UICollectionView { 
	internal func register(_ nib: XibProtocol) -> Void {
		register(nib.nib(), forCellWithReuseIdentifier: nib.name)
	}
	internal func register(nibs: [XibProtocol]) -> Void {
		nibs.forEach(register)
	}
	 
} 

extension EventViewController { 
	class func initialViewController() -> EventViewController {
		let storyboard = UIStoryboard(name: "Event", bundle: nil) 
		let viewController = storyboard.instantiateInitialViewController() as! EventViewController
		return viewController
	}
	 
} 

extension YouTubeListViewController { 
	class func initialViewController() -> YouTubeListViewController {
		let storyboard = UIStoryboard(name: "YouTubeList", bundle: nil) 
		let viewController = storyboard.instantiateInitialViewController() as! YouTubeListViewController
		return viewController
	}
	 
} 

extension MilkListViewController { 
	class func initialViewController() -> MilkListViewController {
		let storyboard = UIStoryboard(name: "MilkList", bundle: nil) 
		let viewController = storyboard.instantiateInitialViewController() as! MilkListViewController
		return viewController
	}
	 
} 
extension UITableViewCell { 
	
	struct Reusable {
		static let youTubeContentsCell: String = "youTubeContentsCell"
	
	} 
} 
extension UIImage { 
	
	struct Asset {
		static let ic_chat_bubble_outline_36pt: UIImage = UIImage(named: "ic_chat_bubble_outline_36pt")!
		static let unchi_character: UIImage = UIImage(named: "unchi_character")!
		static let ic_play_circle_outline_36pt: UIImage = UIImage(named: "ic_play_circle_outline_36pt")!
		static let ic_mode_edit_36pt: UIImage = UIImage(named: "ic_mode_edit_36pt")!
		static let baby_honyubin: UIImage = UIImage(named: "baby_honyubin")!
		static let ic_close_36pt: UIImage = UIImage(named: "ic_close_36pt")!
		static let ic_grid_on_36pt: UIImage = UIImage(named: "ic_grid_on_36pt")!
		static let right_sweets_mizufusen_icecream: UIImage = UIImage(named: "right_sweets_mizufusen_icecream")!
		static let syoubenkozou: UIImage = UIImage(named: "syoubenkozou")!
		static let left_sweets_mizufusen_icecream: UIImage = UIImage(named: "left_sweets_mizufusen_icecream")!
	
	}
	struct Resource {
	
	
	} 
} 

extension String { 
	
	struct Localized {
	
	
	} 
} 

